version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release
os: Visual Studio 2015

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - ps: .\Deploy\install-fxmicroframework-43-44.ps1

build_script:
  - cmd: build-release.cmd

after_test:
  - ps: .\Deploy\pack.ps1  

artifacts:
  - path: '**\*.nupkg' 